version: '3.8'

# Usage: docker-compose -f docker-compose.engine.yml up --build

services:
  redis:
    image: redis:7-alpine
    container_name: easypath_engine_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  engine:
    build:
      context: ./apps/engine
      dockerfile: Dockerfile.dev
    container_name: easypath_engine
    ports:
      - "8081:8081"
    volumes:
      - ./apps/engine:/app
      - ./apps/engine/tests/fixtures:/app/fixtures
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379/0
    #   - LLM_PROVIDER=deepseek
    #   - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
    #   - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
    #   - GEMINI_PROVIDER_MODE=api
    env_file:
      - ./apps/engine/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8081 --reload
    restart: unless-stopped

volumes:
  redis_data: