# Platform services only (Backend + PostgreSQL)
# Usage: docker compose -f docker/docker-compose.yml up
# Or use the helper script: ./scripts/start-platform.sh

services:
  postgres:
    image: postgres:13
    container_name: easypath_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: easypath
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d easypath"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../apps/platform/backend
    container_name: easypath_backend
    ports:
      - "8000:8000"
    volumes:
      - ../apps/platform/backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://user:password@postgres/easypath"
      CORS_ORIGINS: "http://localhost:5173"

volumes:
  postgres_data:
